// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// exports.cpp
integers first_fit_decreasing_fast(doubles x, double cap);
extern "C" SEXP _binpackr_first_fit_decreasing_fast(SEXP x, SEXP cap) {
  BEGIN_CPP11
    return cpp11::as_sexp(first_fit_decreasing_fast(cpp11::as_cpp<cpp11::decay_t<doubles>>(x), cpp11::as_cpp<cpp11::decay_t<double>>(cap)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_binpackr_first_fit_decreasing_fast", (DL_FUNC) &_binpackr_first_fit_decreasing_fast, 2},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_binpackr(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
